### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [rossmeryrojp/Proyecto-1#1]
**README**
* Buen trabajo en incluir decisiones de diseño en tu ReadMe.

**HTML**
* Te sugerimos incluir el atributo `alt` en imágenes para describir la imagen.
* Para seguir buenas prácticas, te sugerimos definir los `id` y `clases` de elementos en minúsculas y separados por guiones (-).
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Frossmeryrojp.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F) para que observes tus errores.

**JS**
* Tu aplicación no cifra/descifra cuando se usa números grandes (Ej: 1042) como offset. Te sugerimos que al momento de desarrollar alguna función trates de probar con varios números y hasta con valores o argumentos “extremos”. Recuerda que tu usuario puede "probar" con cualquier número.
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en `ES6`. Te sugerimos aplicarlo en las definiciones de funciones y loops.
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).

**CSS**
* Para lograr que tu aplicación se vea mejor en pantallas pequeñas, te sugerimos usar [media queries](https://css-tricks.com/logic-in-media-queries/).

**TESTS**
* Te recomendamos apoyarte en los tests para poder hacer pruebas de valores extremos, como usar el offset 1042.

Buen trabajo!

**Comment by rossmeryrojp** [comment]
Gracias por el feedback, mejoraré el proyecto y en adelante tendré presente los alcances.
